analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4785177
  brandStrength: 0
  lightness: 0.9350161
  brandColors:
    - '#2D549F'
    - '#518ED1'
    - '#0B0B0D'
    - '#FFFFFF'
    - '#D7986D'
  rhythmicContrast: 0.4559613
typography_spectrum: 0.8157895
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2207304
favicon: null
name: Inese
